### ISSUE TITLE
hot update 

### ISSUE THREAD

**Issue by leefj** [Wpdas/SWFCacheIOS#1] opened 2016-11-11 14:32 UTC
hi , some question about this cache

1、can this hot update an app without  reinstall ?
2、can host swf call a function in swf that loaded by by cache, or a cached swf can call function in host swf, can i get the class list in cached swf  ? 

3, can cached swf invoke an ANE ?

**Comment by leefj** [comment] 2016-11-11 15:15
i have test your code  , it crashed in ios ! 

BTW IN my swf is not just ui but codes 
[ModuleA.swf.zip](https://github.com/Wpdas/SWFCacheIOS/files/586063/ModuleA.swf.zip)

can you load this swf ?

**Comment by leefj** [comment] 2016-11-11 15:16
the only way i know is load swf as a worker

**Comment by wpdas** [comment] 2016-11-11 16:07
Hi Leefj, yes, you can load class hosted on swf. But for this, you need compile this SWF with a code that give you access. You can access function in other SWF Classes.

All the tests I did, I compiled the SWF along with the main project.

I will test your SWF. Briefly I give you a return.

**Comment by wpdas** [comment] 2016-11-11 16:15
What should I access within this SWF?

**Comment by wpdas** [comment] 2016-11-11 23:52
I can load your SWF file using Air SDK 23 it worked for me. Was printed "模块(ModuleA)域：@2c871811aa01"!

You can call ANE in project setup, don't on your SWF. ANE files are compiled on final project, don't inside of swf.

I don't did not use others SDK versions.

**Comment by leefj** [comment] 2016-11-11 23:57
Yes, i use AIR 23;
Do you load my swf in ios and package project as ipa install in iphone ? 

my app is cashed

**Comment by leefj** [comment] 2016-11-12 00:00
here is my code ,when i install my pacakged ipa in iphone , it crashed  !

```
setTimeout(function():void  {
                testIOs();
            },2000);

private function testIOs():void
        {
            SWFCacheIOS.instance.addEventListener(Event.COMPLETE, onLoadSWFComplete);
            trace("开始载入模块A")
            SWFCacheIOS.instance.load(new URLRequest("/modules/ModuleA.swf"));

        } 

        protected function onLoadSWFComplete(event:Event):void
        {
            trace("已经载入模块A")
            addChild(SWFCacheIOS.instance.getLoadedSWF.content);

        }
```

**Comment by wpdas** [comment] 2016-11-12 00:14
You can send me a simple model of your project?
What iOS version?
Yes, it work for me!

I published recently two apps using this SWFCacheIOS. Search for "fanatikids galo". The games into this app are using this method.

**Comment by leefj** [comment] 2016-11-12 00:24
OK，I will create and  post a sample app project later ,thanks

**Comment by leefj** [comment] 2016-11-12 00:25
ios 10.1.1

**Comment by wpdas** [comment] 2016-11-12 00:29
Its ok! Show me the error on output console on debug please.

**Comment by leefj** [comment] 2016-11-12 00:44
output no error,just crashed

**Comment by wpdas** [comment] 2016-11-12 00:45
You include the "/modules/ModuleA.swf" file in your project?

**Comment by wpdas** [comment] 2016-11-12 00:47
Try load a empty swf. If dont crash, the problem is your ModuleA.swf file.

**Comment by leefj** [comment] 2016-11-12 01:00
i create an empty as3 mobile project , load same swf moduleA,it is loaded and printed 
"模块(ModuleA)域：@2c871811aa01"

it is loaded and run !

i will test more in a complex project with more classes

**Comment by wpdas** [comment] 2016-11-12 01:05
Excellent. Can I close this issue?

**Comment by leefj** [comment] 2016-11-12 01:15
no , when i put the Starling and Feathers UI  and other SWCs, the app crash again !

**Comment by leefj** [comment] 2016-11-12 01:17
i will find the bug point in my code , it is a interesting work ；

**Comment by wpdas** [comment] 2016-11-12 01:18
You put these frameworks inside the loaded swf?

**Comment by leefj** [comment] 2016-11-12 01:19
yes!

**Comment by wpdas** [comment] 2016-11-12 01:21
So, the bug are in your code? Because, when I tested load somethings in other swf, it worked.

**Comment by leefj** [comment] 2016-11-12 01:24
ok , i will find the bug in my code tonight . now i have to leave now .

**Comment by wpdas** [comment] 2016-11-12 01:25
Ok, thanks. I wait your feedback.

**Comment by leefj** [comment] 2016-11-13 00:04
some mesage to feed back

1、when i load a swf from web url , the mobile report this

![img_9840](https://cloud.githubusercontent.com/assets/12420137/20242825/98c068ee-a977-11e6-8913-d5d358cf3ed4.jpg)

2  then i un zip an ipa file ,and find the main swf , it seems loaded and run,but it report this

[Starling] Context ready. Display Driver: OpenGL (Standard Extended)
load http://114.55.1.228:8080/images/modules/ModuleB.swf
[SWF] /images/modules/ModuleB.swf - 解压缩后为 1,994,429 个字节
VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.

**Comment by leefj** [comment] 2016-11-13 00:48
hi, i think i have find the problem, the swf to load can not include Starling swc

**Comment by leefj** [comment] 2016-11-13 02:12
this is my demo project , i load moduleA and module B  in main swf. moduleA only call a function that create a Quad, it will not include starling or feathersui .  in moduleB i direct use Quad , when I click "load module B" button ,the app crashed

[iOSLoadSwfDemo.zip](https://github.com/Wpdas/SWFCacheIOS/files/587555/iOSLoadSwfDemo.zip)

**Comment by leefj** [comment] 2016-11-16 06:27
hi, my friend, are you there?  i have feedback my test result, pls check!

**Comment by leefj** [comment] 2016-11-16 11:59
some thing news

i do some more test 

**( case 1 )**  load load 2 swf crash. ModuleA.swf  first class is "ModuleA" witch extends "Module" class, andModuleB.swf first class is "ModuleB" witch extends "Module" class too. ModuleA.swf load success, but when i load  ModuleB.swf , App is crashed.

**(case 2)** so i unload  the ModuleA.swf before load ModuleB.swf use this code

moduleLoader.unloadAndStop(true);

when i try to load ModuleB.swf the app is crashed too!

**Comment by wpdas** [comment] 2016-11-17 23:24
Hello. I are busy last days, sorry. I will see your Demo and give you a feedback.

**Comment by leefj** [comment] 2016-11-30 02:12
new test:
i load my swf success in ios,but when i load a worker later , the app crashed

**Comment by leefj** [comment] 2016-11-30 02:56
this may not a bug of SWFCacheIOS, it seems load a worker on iOS 9.3 crashed(debug mode)

**Comment by leefj** [comment] 2016-11-30 03:00
my god, it seems ok, when i package an ipa and install on iPhone, both module swf and worker is loaded

**Closed as completed** 2017-04-17 07:06 UTC
